favicon: /favicon.ico

manifest: /manifest.json

show_excerpt: false

color_scheme: auto

show_color_scheme_toggle: true

nav:
  title: LoveStory
  items:
    Archives: /archives
    About: /about
    Resume: /resume
    GitHub: https://github.com/bingling-sama/Love

footer:
  Story:
    Story: /
    Archives: /archives
  About:
    About: /about
    Resume: /resume
  Me:
    GitHub: https://github.com/bingling-sama
    Email: bingling_sama@qq.com

license: CC BY-NC 4.0
license_link: https://creativecommons.org/licenses/by-nc/4.0
